### ISSUE TITLE
Email provider with link/info to enable them to register with Catapillr

### ISSUE THREAD

**Issue by lucymk** [Catapillr/loan-application-platform#106]
- [x] generate magic link which gets emailed to provider (contains companies house number if exists)
- [x] connect payment somehow so it gets sent once provider has been registered
- [x] link goes to provider onboarding flow 
- [x] if companies house number provided info is prepopulated from api call
- [x] if no companies house number then provider has to fill in all data themselves
- [x] form may need to be rendered slightly differently if companies house registered or not
